// This file was generated by liblab | https://liblab.com/

using OpenHue;
using OpenHue.Config;
using Environment = OpenHue.Http.Environment;

var apiKeyConfig = new ApiKeyAuthConfig("YOUR_API_KEY");

var config = new OpenHueConfig { Environment = Environment.Default, ApiKeyAuth = apiKeyConfig };

var client = new OpenHueClient(config);

var response = await client.Resource.GetResourcesAsync();

Console.WriteLine(response);
