// This file was generated by liblab | https://liblab.com/

namespace OpenHue.Config;

public record ApiKeyAuthConfig(
    string ApiKey,
    string? ApiKeyHeader = ApiKeyAuthConfig.DefaultApiKeyHeader
)
{
    public const string DefaultApiKeyHeader = "hue-application-key";
}
