// This file was generated by liblab | https://liblab.com/

using Environment = OpenHue.Http.Environment;

namespace OpenHue.Config;

/// <summary>
/// Configuration options for the OpenHueClient.
/// </summary>
public record OpenHueConfig(
    /// <value>The environment to use for the SDK.</value>
    Environment? Environment = null,
    /// <value>The api-key authentication configuration.</value>
    ApiKeyAuthConfig? ApiKeyAuth = null
);
