// This file was generated by liblab | https://liblab.com/

using Environment = NhlClient.Http.Environment;

namespace NhlClient.Config;

/// <summary>
/// Configuration options for the NhlClientClient.
/// </summary>
public record NhlClientConfig(
    /// <value>The environment to use for the SDK.</value>
    Environment? Environment = null
);
