// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace OpenHue.Models;

/// <summary>Joined alert control</summary>
public record Alert(
    [property:
        JsonPropertyName("action"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Action = null
);
