// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace OpenHue.Models;

public record AuthenticateRequest(
    [property:
        JsonPropertyName("devicetype"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Devicetype = null,
    [property:
        JsonPropertyName("generateclientkey"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        bool? Generateclientkey = null
);
