// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace OpenHue.Models;

public record ColorTemperaturePalettePost(
    [property:
        JsonPropertyName("color_temperature"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ColorTemperaturePalettePost.ColorTemperaturePalettePostColorTemperature? ColorTemperature =
        null,
    [property:
        JsonPropertyName("dimming"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        Dimming? Dimming = null
)
{
    public record ColorTemperaturePalettePostColorTemperature(
        /// <value>color temperature in mirek or null when the light color is not in the ct spectrum</value>
        [property:
            JsonPropertyName("mirek"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            long? Mirek = null
    );
}
