// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace OpenHue.Models;

public record Color(
    /// <value>CIE XY gamut position</value>
    [property: JsonPropertyName("xy"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        GamutPosition? Xy = null
);
