// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using OpenHue.Json;

namespace OpenHue.Models;

public record ColorTemperatureDelta(
    [property:
        JsonPropertyName("action"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ColorTemperatureDelta.ColorTemperatureDeltaAction? Action = null,
    /// <value>Mirek delta to current mirek. Clip at mirek_minimum and mirek_maximum of mirek_schema.</value>
    [property:
        JsonPropertyName("mirek_delta"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? MirekDelta = null
)
{
    public record ColorTemperatureDeltaAction : ValueEnum<string>
    {
        internal ColorTemperatureDeltaAction(string value)
            : base(value) { }

        public ColorTemperatureDeltaAction()
            : base("up") { }

        public static ColorTemperatureDeltaAction Up = new("up");
        public static ColorTemperatureDeltaAction Down = new("down");
        public static ColorTemperatureDeltaAction Stop = new("stop");
    }
}
