// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using OpenHue.Json;

namespace OpenHue.Models;

public record DimmingDelta(
    [property:
        JsonPropertyName("action"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        DimmingDelta.DimmingDeltaAction? Action = null,
    /// <value>
    /// Brightness percentage of full-scale increase delta to current dimlevel. Clip at Max-level or Min-level.
    /// </value>
    [property:
        JsonPropertyName("brightness_delta"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? BrightnessDelta = null
)
{
    public record DimmingDeltaAction : ValueEnum<string>
    {
        internal DimmingDeltaAction(string value)
            : base(value) { }

        public DimmingDeltaAction()
            : base("up") { }

        public static DimmingDeltaAction Up = new("up");
        public static DimmingDeltaAction Down = new("down");
        public static DimmingDeltaAction Stop = new("stop");
    }
}
