// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace OpenHue.Models;

public record Dimming(
    /// <value>Brightness percentage. value cannot be 0, writing 0 changes it to lowest possible brightness</value>
    [property:
        JsonPropertyName("brightness"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Brightness = null
);
