// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace OpenHue.Models;

public record Dynamics(
    /// <value>Duration of a light transition or timed effects in ms.</value>
    [property:
        JsonPropertyName("duration"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? Duration = null,
    /// <value>
    /// Speed of dynamic palette or effect.
    /// The speed is valid for the dynamic palette if the status is `dynamic_palette` or for the corresponding effect listed in status.
    /// In case of status `none`, the speed is not valid.
    /// </value>
    [property:
        JsonPropertyName("speed"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Speed = null
);
