// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace OpenHue.Models;

/// <summary>CIE XY gamut position</summary>
public record GamutPosition(
    /// <value>X position in color gamut</value>
    [property: JsonPropertyName("x"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        double? X = null,
    /// <value>y position in color gamut</value>
    [property: JsonPropertyName("y"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        double? Y = null
);
