// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace OpenHue.Models;

/// <summary>Basic feature containing gradient properties.</summary>
public record Gradient(
    /// <value>Collection of gradients points. For control of the gradient points through a PUT a minimum of 2 points need to be provided.</value>
    [property:
        JsonPropertyName("points"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<Color>? Points = null,
    /// <value>Mode in which the points are currently being deployed. If not provided during PUT/POST it will be defaulted to interpolated_palette</value>
    [property:
        JsonPropertyName("mode"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        SupportedGradientMode? Mode = null
);
