// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using OpenHue.Json;

namespace OpenHue.Models;

/// <summary>Light archetype</summary>
public record LightArchetype : ValueEnum<string>
{
    internal LightArchetype(string value)
        : base(value) { }

    public LightArchetype()
        : base("unknown_archetype") { }

    public static LightArchetype UnknownArchetype = new("unknown_archetype");
    public static LightArchetype ClassicBulb = new("classic_bulb");
    public static LightArchetype SultanBulb = new("sultan_bulb");
    public static LightArchetype FloodBulb = new("flood_bulb");
    public static LightArchetype SpotBulb = new("spot_bulb");
    public static LightArchetype CandleBulb = new("candle_bulb");
    public static LightArchetype LusterBulb = new("luster_bulb");
    public static LightArchetype PendantRound = new("pendant_round");
    public static LightArchetype PendantLong = new("pendant_long");
    public static LightArchetype CeilingRound = new("ceiling_round");
    public static LightArchetype CeilingSquare = new("ceiling_square");
    public static LightArchetype FloorShade = new("floor_shade");
    public static LightArchetype FloorLantern = new("floor_lantern");
    public static LightArchetype TableShade = new("table_shade");
    public static LightArchetype RecessedCeiling = new("recessed_ceiling");
    public static LightArchetype RecessedFloor = new("recessed_floor");
    public static LightArchetype SingleSpot = new("single_spot");
    public static LightArchetype DoubleSpot = new("double_spot");
    public static LightArchetype TableWash = new("table_wash");
    public static LightArchetype WallLantern = new("wall_lantern");
    public static LightArchetype WallShade = new("wall_shade");
    public static LightArchetype FlexibleLamp = new("flexible_lamp");
    public static LightArchetype GroundSpot = new("ground_spot");
    public static LightArchetype WallSpot = new("wall_spot");
    public static LightArchetype Plug = new("plug");
    public static LightArchetype HueGo = new("hue_go");
    public static LightArchetype HueLightstrip = new("hue_lightstrip");
    public static LightArchetype HueIris = new("hue_iris");
    public static LightArchetype HueBloom = new("hue_bloom");
    public static LightArchetype Bollard = new("bollard");
    public static LightArchetype WallWasher = new("wall_washer");
    public static LightArchetype HuePlay = new("hue_play");
    public static LightArchetype VintageBulb = new("vintage_bulb");
    public static LightArchetype VintageCandleBulb = new("vintage_candle_bulb");
    public static LightArchetype EllipseBulb = new("ellipse_bulb");
    public static LightArchetype TriangleBulb = new("triangle_bulb");
    public static LightArchetype SmallGlobeBulb = new("small_globe_bulb");
    public static LightArchetype LargeGlobeBulb = new("large_globe_bulb");
    public static LightArchetype EdisonBulb = new("edison_bulb");
    public static LightArchetype ChristmasTree = new("christmas_tree");
    public static LightArchetype StringLight = new("string_light");
    public static LightArchetype HueCentris = new("hue_centris");
    public static LightArchetype HueLightstripTv = new("hue_lightstrip_tv");
    public static LightArchetype HueLightstripPc = new("hue_lightstrip_pc");
    public static LightArchetype HueTube = new("hue_tube");
    public static LightArchetype HueSigne = new("hue_signe");
    public static LightArchetype PendantSpot = new("pendant_spot");
    public static LightArchetype CeilingHorizontal = new("ceiling_horizontal");
    public static LightArchetype CeilingTube = new("ceiling_tube");
}
