// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace OpenHue.Models;

public record MotionPut(
    /// <value>Type of the supported resources (always `motion` here)</value>
    [property:
        JsonPropertyName("type"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Type_ = null,
    /// <value>true when the sensor is activated, false when deactivated</value>
    [property:
        JsonPropertyName("enabled"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        bool? Enabled = null,
    [property:
        JsonPropertyName("sensitivity"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        MotionPut.MotionPutSensitivity? Sensitivity = null
)
{
    public record MotionPutSensitivity(
        /// <value>Sensitivity of the sensor. Value in the range 0 to sensitivity_max.</value>
        [property:
            JsonPropertyName("sensitivity"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            long? Sensitivity = null
    );
}
