// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using OpenHue.Json;

namespace OpenHue.Models;

/// <summary>The default archetype given by manufacturer. Can be changed by user.</summary>
public record ProductArchetype : ValueEnum<string>
{
    internal ProductArchetype(string value)
        : base(value) { }

    public ProductArchetype()
        : base("bridge_v2") { }

    public static ProductArchetype BridgeV2 = new("bridge_v2");
    public static ProductArchetype UnknownArchetype = new("unknown_archetype");
    public static ProductArchetype ClassicBulb = new("classic_bulb");
    public static ProductArchetype SultanBulb = new("sultan_bulb");
    public static ProductArchetype FloodBulb = new("flood_bulb");
    public static ProductArchetype SpotBulb = new("spot_bulb");
    public static ProductArchetype CandleBulb = new("candle_bulb");
    public static ProductArchetype LusterBulb = new("luster_bulb");
    public static ProductArchetype PendantRound = new("pendant_round");
    public static ProductArchetype PendantLong = new("pendant_long");
    public static ProductArchetype CeilingRound = new("ceiling_round");
    public static ProductArchetype CeilingSquare = new("ceiling_square");
    public static ProductArchetype FloorShade = new("floor_shade");
    public static ProductArchetype FloorLantern = new("floor_lantern");
    public static ProductArchetype TableShade = new("table_shade");
    public static ProductArchetype RecessedCeiling = new("recessed_ceiling");
    public static ProductArchetype RecessedFloor = new("recessed_floor");
    public static ProductArchetype SingleSpot = new("single_spot");
    public static ProductArchetype DoubleSpot = new("double_spot");
    public static ProductArchetype TableWash = new("table_wash");
    public static ProductArchetype WallLantern = new("wall_lantern");
    public static ProductArchetype WallShade = new("wall_shade");
    public static ProductArchetype FlexibleLamp = new("flexible_lamp");
    public static ProductArchetype GroundSpot = new("ground_spot");
    public static ProductArchetype WallSpot = new("wall_spot");
    public static ProductArchetype Plug = new("plug");
    public static ProductArchetype HueGo = new("hue_go");
    public static ProductArchetype HueLightstrip = new("hue_lightstrip");
    public static ProductArchetype HueIris = new("hue_iris");
    public static ProductArchetype HueBloom = new("hue_bloom");
    public static ProductArchetype Bollard = new("bollard");
    public static ProductArchetype WallWasher = new("wall_washer");
    public static ProductArchetype HuePlay = new("hue_play");
    public static ProductArchetype VintageBulb = new("vintage_bulb");
    public static ProductArchetype VintageCandleBulb = new("vintage_candle_bulb");
    public static ProductArchetype EllipseBulb = new("ellipse_bulb");
    public static ProductArchetype TriangleBulb = new("triangle_bulb");
    public static ProductArchetype SmallGlobeBulb = new("small_globe_bulb");
    public static ProductArchetype LargeGlobeBulb = new("large_globe_bulb");
    public static ProductArchetype EdisonBulb = new("edison_bulb");
    public static ProductArchetype ChristmasTree = new("christmas_tree");
    public static ProductArchetype StringLight = new("string_light");
    public static ProductArchetype HueCentris = new("hue_centris");
    public static ProductArchetype HueLightstripTv = new("hue_lightstrip_tv");
    public static ProductArchetype HueLightstripPc = new("hue_lightstrip_pc");
    public static ProductArchetype HueTube = new("hue_tube");
    public static ProductArchetype HueSigne = new("hue_signe");
    public static ProductArchetype PendantSpot = new("pendant_spot");
    public static ProductArchetype CeilingHorizontal = new("ceiling_horizontal");
    public static ProductArchetype CeilingTube = new("ceiling_tube");
}
