// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using OpenHue.Json;

namespace OpenHue.Models;

public record ResourceGet(
    /// <value>Type of the supported resources</value>
    [property:
        JsonPropertyName("type"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ResourceGet.ResourceGetType? Type_ = null,
    /// <value>Unique identifier representing a specific resource instance</value>
    [property: JsonPropertyName("id"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        string? Id = null,
    /// <value>Clip v1 resource identifier</value>
    [property:
        JsonPropertyName("id_v1"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? IdV1 = null,
    [property:
        JsonPropertyName("owner"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ResourceIdentifier? Owner = null
)
{
    /// <summary>Type of the supported resources</summary>
    public record ResourceGetType : ValueEnum<string>
    {
        internal ResourceGetType(string value)
            : base(value) { }

        public ResourceGetType()
            : base("device") { }

        public static ResourceGetType Device = new("device");
        public static ResourceGetType BridgeHome = new("bridge_home");
        public static ResourceGetType Room = new("room");
        public static ResourceGetType Zone = new("zone");
        public static ResourceGetType Light = new("light");
        public static ResourceGetType Button = new("button");
        public static ResourceGetType RelativeRotary = new("relative_rotary");
        public static ResourceGetType Temperature = new("temperature");
        public static ResourceGetType LightLevel = new("light_level");
        public static ResourceGetType Motion = new("motion");
        public static ResourceGetType CameraMotion = new("camera_motion");
        public static ResourceGetType Entertainment = new("entertainment");
        public static ResourceGetType Contact = new("contact");
        public static ResourceGetType Tamper = new("tamper");
        public static ResourceGetType GroupedLight = new("grouped_light");
        public static ResourceGetType DevicePower = new("device_power");
        public static ResourceGetType ZigbeeBridgeConnectivity = new("zigbee_bridge_connectivity");
        public static ResourceGetType ZigbeeConnectivity = new("zigbee_connectivity");
        public static ResourceGetType ZgpConnectivity = new("zgp_connectivity");
        public static ResourceGetType Bridge = new("bridge");
        public static ResourceGetType ZigbeeDeviceDiscovery = new("zigbee_device_discovery");
        public static ResourceGetType Homekit = new("homekit");
        public static ResourceGetType Matter = new("matter");
        public static ResourceGetType MatterFabric = new("matter_fabric");
        public static ResourceGetType Scene = new("scene");
        public static ResourceGetType EntertainmentConfiguration =
            new("entertainment_configuration");
        public static ResourceGetType PublicImage = new("public_image");
        public static ResourceGetType AuthV1 = new("auth_v1");
        public static ResourceGetType BehaviorScript = new("behavior_script");
        public static ResourceGetType BehaviorInstance = new("behavior_instance");
        public static ResourceGetType Geofence = new("geofence");
        public static ResourceGetType GeofenceClient = new("geofence_client");
        public static ResourceGetType Geolocation = new("geolocation");
        public static ResourceGetType SmartScene = new("smart_scene");
    }
}
