// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using OpenHue.Json;

namespace OpenHue.Models;

public record ResourceIdentifier(
    /// <value>The unique id of the referenced resource</value>
    [property:
        JsonPropertyName("rid"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Rid = null,
    /// <value>The type of the referenced resource</value>
    [property:
        JsonPropertyName("rtype"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ResourceIdentifier.Rtype? Rtype_ = null
)
{
    /// <summary>The type of the referenced resource</summary>
    public record Rtype : ValueEnum<string>
    {
        internal Rtype(string value)
            : base(value) { }

        public Rtype()
            : base("device") { }

        public static Rtype Device = new("device");
        public static Rtype BridgeHome = new("bridge_home");
        public static Rtype Room = new("room");
        public static Rtype Zone = new("zone");
        public static Rtype Light = new("light");
        public static Rtype Button = new("button");
        public static Rtype RelativeRotary = new("relative_rotary");
        public static Rtype Temperature = new("temperature");
        public static Rtype LightLevel = new("light_level");
        public static Rtype Motion = new("motion");
        public static Rtype CameraMotion = new("camera_motion");
        public static Rtype Entertainment = new("entertainment");
        public static Rtype Contact = new("contact");
        public static Rtype Tamper = new("tamper");
        public static Rtype GroupedLight = new("grouped_light");
        public static Rtype DevicePower = new("device_power");
        public static Rtype ZigbeeBridgeConnectivity = new("zigbee_bridge_connectivity");
        public static Rtype ZigbeeConnectivity = new("zigbee_connectivity");
        public static Rtype ZgpConnectivity = new("zgp_connectivity");
        public static Rtype Bridge = new("bridge");
        public static Rtype ZigbeeDeviceDiscovery = new("zigbee_device_discovery");
        public static Rtype Homekit = new("homekit");
        public static Rtype Matter = new("matter");
        public static Rtype MatterFabric = new("matter_fabric");
        public static Rtype Scene = new("scene");
        public static Rtype EntertainmentConfiguration = new("entertainment_configuration");
        public static Rtype PublicImage = new("public_image");
        public static Rtype AuthV1 = new("auth_v1");
        public static Rtype BehaviorScript = new("behavior_script");
        public static Rtype BehaviorInstance = new("behavior_instance");
        public static Rtype Geofence = new("geofence");
        public static Rtype GeofenceClient = new("geofence_client");
        public static Rtype Geolocation = new("geolocation");
        public static Rtype SmartScene = new("smart_scene");
    }
}
