// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using OpenHue.Json;

namespace OpenHue.Models;

/// <summary>Possible archetypes of a room</summary>
public record RoomArchetype : ValueEnum<string>
{
    internal RoomArchetype(string value)
        : base(value) { }

    public RoomArchetype()
        : base("living_room") { }

    public static RoomArchetype LivingRoom = new("living_room");
    public static RoomArchetype Kitchen = new("kitchen");
    public static RoomArchetype Dining = new("dining");
    public static RoomArchetype Bedroom = new("bedroom");
    public static RoomArchetype KidsBedroom = new("kids_bedroom");
    public static RoomArchetype Bathroom = new("bathroom");
    public static RoomArchetype Nursery = new("nursery");
    public static RoomArchetype Recreation = new("recreation");
    public static RoomArchetype Office = new("office");
    public static RoomArchetype Gym = new("gym");
    public static RoomArchetype Hallway = new("hallway");
    public static RoomArchetype Toilet = new("toilet");
    public static RoomArchetype FrontDoor = new("front_door");
    public static RoomArchetype Garage = new("garage");
    public static RoomArchetype Terrace = new("terrace");
    public static RoomArchetype Garden = new("garden");
    public static RoomArchetype Driveway = new("driveway");
    public static RoomArchetype Carport = new("carport");
    public static RoomArchetype Home = new("home");
    public static RoomArchetype Downstairs = new("downstairs");
    public static RoomArchetype Upstairs = new("upstairs");
    public static RoomArchetype TopFloor = new("top_floor");
    public static RoomArchetype Attic = new("attic");
    public static RoomArchetype GuestRoom = new("guest_room");
    public static RoomArchetype Staircase = new("staircase");
    public static RoomArchetype Lounge = new("lounge");
    public static RoomArchetype ManCave = new("man_cave");
    public static RoomArchetype Computer = new("computer");
    public static RoomArchetype Studio = new("studio");
    public static RoomArchetype Music = new("music");
    public static RoomArchetype Tv = new("tv");
    public static RoomArchetype Reading = new("reading");
    public static RoomArchetype Closet = new("closet");
    public static RoomArchetype Storage = new("storage");
    public static RoomArchetype LaundryRoom = new("laundry_room");
    public static RoomArchetype Balcony = new("balcony");
    public static RoomArchetype Porch = new("porch");
    public static RoomArchetype Barbecue = new("barbecue");
    public static RoomArchetype Pool = new("pool");
    public static RoomArchetype Other = new("other");
}
