// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using OpenHue.Json;

namespace OpenHue.Models;

public record ScenePut(
    [property:
        JsonPropertyName("type"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ScenePut.ScenePutType? Type_ = null,
    /// <value>List of actions to be executed synchronously on recall</value>
    [property:
        JsonPropertyName("actions"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<ActionPost>? Actions = null,
    [property:
        JsonPropertyName("recall"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        SceneRecall? Recall = null,
    [property:
        JsonPropertyName("metadata"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        SceneMetadata? Metadata = null,
    /// <value>Group of colors that describe the palette of colors to be used when playing dynamics</value>
    [property:
        JsonPropertyName("palette"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ScenePalette? Palette = null,
    /// <value>Speed of dynamic palette for this scene</value>
    [property:
        JsonPropertyName("speed"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Speed = null,
    /// <value>Indicates whether to automatically start the scene dynamically on active recall</value>
    [property:
        JsonPropertyName("auto_dynamic"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        bool? AutoDynamic = null
)
{
    public record ScenePutType : ValueEnum<string>
    {
        internal ScenePutType(string value)
            : base(value) { }

        public ScenePutType()
            : base("scene") { }

        public static ScenePutType Scene = new("scene");
    }
}
