// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace OpenHue.Models;

/// <summary>Group of colors that describe the palette of colors to be used when playing dynamics</summary>
public record ScenePalette(
    [property:
        JsonPropertyName("color"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<ColorPaletteGet>? Color = null,
    [property:
        JsonPropertyName("dimming"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<Dimming>? Dimming = null,
    [property:
        JsonPropertyName("color_temperature"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<ColorTemperaturePalettePost>? ColorTemperature = null,
    [property:
        JsonPropertyName("effects"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<ScenePalette.ScenePaletteEffects>? Effects = null
)
{
    public record ScenePaletteEffects(
        [property:
            JsonPropertyName("effect"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            SupportedEffects? Effect = null
    );
}
