// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using OpenHue.Json;

namespace OpenHue.Models;

public record SceneRecall(
    /// <value>When writing active, the actions in the scene are executed on the target. dynamic_palette starts dynamic scene with colors in the Palette object.</value>
    [property:
        JsonPropertyName("action"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        SceneRecall.SceneRecallAction? Action = null,
    /// <value>Transition to the scene within the timeframe given by duration</value>
    [property:
        JsonPropertyName("duration"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? Duration = null,
    [property:
        JsonPropertyName("dimming"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        Dimming? Dimming = null
)
{
    /// <summary>When writing active, the actions in the scene are executed on the target. dynamic_palette starts dynamic scene with colors in the Palette object.</summary>
    public record SceneRecallAction : ValueEnum<string>
    {
        internal SceneRecallAction(string value)
            : base(value) { }

        public SceneRecallAction()
            : base("active") { }

        public static SceneRecallAction Active = new("active");
        public static SceneRecallAction DynamicPalette = new("dynamic_palette");
        public static SceneRecallAction Static_ = new("static");
    }
}
