// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using OpenHue.Json;

namespace OpenHue.Models;

/// <summary>Mode in which the points are currently being deployed. If not provided during PUT/POST it will be defaulted to interpolated_palette</summary>
public record SupportedGradientMode : ValueEnum<string>
{
    internal SupportedGradientMode(string value)
        : base(value) { }

    public SupportedGradientMode()
        : base("interpolated_palette") { }

    public static SupportedGradientMode InterpolatedPalette = new("interpolated_palette");
    public static SupportedGradientMode InterpolatedPaletteMirrored =
        new("interpolated_palette_mirrored");
    public static SupportedGradientMode RandomPixelated = new("random_pixelated");
}
