// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using OpenHue.Json;

namespace OpenHue.Models;

/// <summary>Current status values the light is in regarding timed effects</summary>
public record SupportedTimedEffects : ValueEnum<string>
{
    internal SupportedTimedEffects(string value)
        : base(value) { }

    public SupportedTimedEffects()
        : base("sunrise") { }

    public static SupportedTimedEffects Sunrise = new("sunrise");
    public static SupportedTimedEffects NoEffect = new("no_effect");
}
