// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using OpenHue.Json;

namespace OpenHue.Models;

/// <summary>Indicates which signal is currently active.</summary>
public record SupportedSignals : ValueEnum<string>
{
    internal SupportedSignals(string value)
        : base(value) { }

    public SupportedSignals()
        : base("no_signal") { }

    public static SupportedSignals NoSignal = new("no_signal");
    public static SupportedSignals OnOff = new("on_off");
    public static SupportedSignals OnOffColor = new("on_off_color");
    public static SupportedSignals Alternating = new("alternating");
}
