// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using NhlClient.Http;
using NhlClient.Http.Exceptions;
using NhlClient.Http.Extensions;
using NhlClient.Http.Serialization;

namespace NhlClient.Services;

public class PlayerService : BaseService
{
    internal PlayerService(HttpClient httpClient)
        : base(httpClient) { }

    /// <summary>Retrieve the game log for a specific player, season, and game type.</summary>
    /// <param name="player">Player ID</param>
    /// <param name="season">Season in YYYYYYYY format</param>
    /// <param name="gameType">Game type (2 for regular season, 3 for playoffs)</param>
    public async Task<object> GetGameLogAsync(
        long player,
        long season,
        long gameType,
        CancellationToken cancellationToken = default
    )
    {
        var request = new RequestBuilder(
            HttpMethod.Get,
            "v1/player/{player}/game-log/{season}/{game-type}"
        )
            .SetPathParameter("player", player)
            .SetPathParameter("season", season)
            .SetPathParameter("game-type", gameType)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>Retrieve information for a specific player.</summary>
    /// <param name="player">Player ID</param>
    public async Task<object> GetPlayerInfoAsync(
        long player,
        CancellationToken cancellationToken = default
    )
    {
        var request = new RequestBuilder(HttpMethod.Get, "v1/player/{player}/landing")
            .SetPathParameter("player", player)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>Retrieve the game log for a specific player as of the current moment.</summary>
    /// <param name="player">Player ID</param>
    public async Task<object> GetGameLogCurrentAsync(
        long player,
        CancellationToken cancellationToken = default
    )
    {
        var request = new RequestBuilder(HttpMethod.Get, "v1/player/{player}/game-log/now")
            .SetPathParameter("player", player)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }
}
