// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using NhlClient.Http;
using NhlClient.Http.Exceptions;
using NhlClient.Http.Extensions;
using NhlClient.Http.Serialization;

namespace NhlClient.Services;

public class RosterService : BaseService
{
    internal RosterService(HttpClient httpClient)
        : base(httpClient) { }

    /// <summary>Retrieve the roster for a specific team as of the current moment.</summary>
    /// <param name="team">Three-letter team code</param>
    public async Task<object> GetCurrentTeamRosterAsync(
        string team,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(team, nameof(team));

        var request = new RequestBuilder(HttpMethod.Get, "v1/roster/{team}/current")
            .SetPathParameter("team", team)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>Retrieve the roster for a specific team and season.</summary>
    /// <param name="team">Three-letter team code</param>
    /// <param name="season">Season in YYYYYYYY format</param>
    public async Task<object> GetTeamRosterBySeasonAsync(
        string team,
        long season,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(team, nameof(team));

        var request = new RequestBuilder(HttpMethod.Get, "v1/roster/{team}/{season}")
            .SetPathParameter("team", team)
            .SetPathParameter("season", season)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }
}
