// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using NhlClient.Http;
using NhlClient.Http.Exceptions;
using NhlClient.Http.Extensions;
using NhlClient.Http.Serialization;

namespace NhlClient.Services;

public class ScheduleService : BaseService
{
    internal ScheduleService(HttpClient httpClient)
        : base(httpClient) { }

    /// <summary>Retrieve the next game for a specific team.</summary>
    /// <param name="team">Three-letter team code</param>
    public async Task<object> GetTeamNextGameAsync(
        string team,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(team, nameof(team));

        var request = new RequestBuilder(HttpMethod.Get, "v1/schedule/{team}/next")
            .SetPathParameter("team", team)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>Retrieve the schedule for a specific team and season.</summary>
    /// <param name="team">Three-letter team code</param>
    /// <param name="season">Season in YYYYYYYY format</param>
    public async Task<object> GetTeamScheduleBySeasonAsync(
        string team,
        long season,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(team, nameof(team));

        var request = new RequestBuilder(HttpMethod.Get, "v1/schedule/{team}/{season}")
            .SetPathParameter("team", team)
            .SetPathParameter("season", season)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>Retrieve the statistics for a specific game.</summary>
    /// <param name="season">Season in YYYYYYYY format</param>
    /// <param name="team">Three-letter team code</param>
    /// <param name="game">Game ID</param>
    public async Task<object> GetGameStatsAsync(
        long season,
        string team,
        long game,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(team, nameof(team));

        var request = new RequestBuilder(
            HttpMethod.Get,
            "v1/schedule/{season}/team/{team}/game/{game}"
        )
            .SetPathParameter("season", season)
            .SetPathParameter("team", team)
            .SetPathParameter("game", game)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }
}
