// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using NhlClient.Http;
using NhlClient.Http.Exceptions;
using NhlClient.Http.Extensions;
using NhlClient.Http.Serialization;

namespace NhlClient.Services;

public class ScoreboardService : BaseService
{
    internal ScoreboardService(HttpClient httpClient)
        : base(httpClient) { }

    /// <summary>Retrieve the scoreboard for a specific team as of the current moment.</summary>
    /// <param name="team">Three-letter team code</param>
    public async Task<object> GetCurrentTeamScoreboardAsync(
        string team,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(team, nameof(team));

        var request = new RequestBuilder(HttpMethod.Get, "v1/scoreboard/{team}/now")
            .SetPathParameter("team", team)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }
}
