// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using NhlClient.Http;
using NhlClient.Http.Exceptions;
using NhlClient.Http.Extensions;
using NhlClient.Http.Serialization;

namespace NhlClient.Services;

public class SkaterStatsService : BaseService
{
    internal SkaterStatsService(HttpClient httpClient)
        : base(httpClient) { }

    /// <summary>Retrieve current skater stats leaders.</summary>
    /// <param name="categories">Categories to filter by</param>
    /// <param name="limit">Limit results (Note: a limit of -1 will return all results)</param>
    public async Task<object> GetCurrentSkaterStatsLeadersAsync(
        string? categories = null,
        long? limit = null,
        CancellationToken cancellationToken = default
    )
    {
        var request = new RequestBuilder(HttpMethod.Get, "v1/skater-stats-leaders/current")
            .SetOptionalQueryParameter("categories", categories)
            .SetOptionalQueryParameter("limit", limit)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>Retrieve skater stats leaders for a specific season and game type.</summary>
    /// <param name="season">Season in YYYYYYYY format</param>
    /// <param name="gameType">Game type (2 for regular season, 3 for playoffs)</param>
    /// <param name="categories">Categories to filter by</param>
    /// <param name="limit">Limit results (Note: a limit of -1 will return all results)</param>
    public async Task<object> GetSkaterStatsLeadersAsync(
        long season,
        long gameType,
        string? categories = null,
        long? limit = null,
        CancellationToken cancellationToken = default
    )
    {
        var request = new RequestBuilder(
            HttpMethod.Get,
            "v1/skater-stats-leaders/{season}/{game-type}"
        )
            .SetPathParameter("season", season)
            .SetPathParameter("game-type", gameType)
            .SetOptionalQueryParameter("categories", categories)
            .SetOptionalQueryParameter("limit", limit)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }
}
