// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using OpenHue.Http;
using OpenHue.Http.Exceptions;
using OpenHue.Http.Extensions;
using OpenHue.Http.Serialization;
using OpenHue.Models;

namespace OpenHue.Services;

public class LightService : BaseService
{
    internal LightService(HttpClient httpClient)
        : base(httpClient) { }

    /// <summary>List all available lights.</summary>
    public async Task<GetLightsOkResponse> GetLightsAsync(
        CancellationToken cancellationToken = default
    )
    {
        var request = new RequestBuilder(HttpMethod.Get, "clip/v2/resource/light").Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<GetLightsOkResponse>(
                    _jsonSerializerOptions,
                    cancellationToken
                )
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>Get details of a single light from its given `{lightId}`.</summary>
    /// <param name="lightId">ID of the light</param>
    public async Task<GetLightOkResponse> GetLightAsync(
        string lightId,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(lightId, nameof(lightId));

        var request = new RequestBuilder(HttpMethod.Get, "clip/v2/resource/light/{lightId}")
            .SetPathParameter("lightId", lightId)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<GetLightOkResponse>(
                    _jsonSerializerOptions,
                    cancellationToken
                )
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>Update a single light from its given `{lightId}`.</summary>
    /// <param name="lightId">ID of the light</param>
    public async Task<UpdateLightOkResponse> UpdateLightAsync(
        LightPut input,
        string lightId,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(input, nameof(input));
        ArgumentNullException.ThrowIfNull(lightId, nameof(lightId));

        var request = new RequestBuilder(HttpMethod.Put, "clip/v2/resource/light/{lightId}")
            .SetPathParameter("lightId", lightId)
            .SetContentAsJson(input, _jsonSerializerOptions)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<UpdateLightOkResponse>(
                    _jsonSerializerOptions,
                    cancellationToken
                )
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }
}
