// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using OpenHue.Http;
using OpenHue.Http.Exceptions;
using OpenHue.Http.Extensions;
using OpenHue.Http.Serialization;
using OpenHue.Models;

namespace OpenHue.Services;

public class MotionService : BaseService
{
    internal MotionService(HttpClient httpClient)
        : base(httpClient) { }

    /// <summary>List all available motion sensors.</summary>
    public async Task<GetMotionSensorsOkResponse> GetMotionSensorsAsync(
        CancellationToken cancellationToken = default
    )
    {
        var request = new RequestBuilder(HttpMethod.Get, "clip/v2/resource/motion").Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<GetMotionSensorsOkResponse>(
                    _jsonSerializerOptions,
                    cancellationToken
                )
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>Get details of a single motion sensor from its given `{motionId}`.</summary>
    /// <param name="motionId">ID of the motion sensor</param>
    public async Task<GetMotionSensorOkResponse> GetMotionSensorAsync(
        string motionId,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(motionId, nameof(motionId));

        var request = new RequestBuilder(HttpMethod.Get, "clip/v2/resource/motion/{motionId}")
            .SetPathParameter("motionId", motionId)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<GetMotionSensorOkResponse>(
                    _jsonSerializerOptions,
                    cancellationToken
                )
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>Update a single motion sensor from its given `{motionId}`.</summary>
    /// <param name="motionId">Id of the motion sensor</param>
    public async Task<UpdateMotionSensorOkResponse> UpdateMotionSensorAsync(
        MotionPut input,
        string motionId,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(input, nameof(input));
        ArgumentNullException.ThrowIfNull(motionId, nameof(motionId));

        var request = new RequestBuilder(HttpMethod.Put, "clip/v2/resource/motion/{motionId}")
            .SetPathParameter("motionId", motionId)
            .SetContentAsJson(input, _jsonSerializerOptions)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<UpdateMotionSensorOkResponse>(
                    _jsonSerializerOptions,
                    cancellationToken
                )
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }
}
