// This file was generated by liblab | https://liblab.com/

namespace NhlClient.Http.Serialization;

public enum SerializationStyle
{
    Simple = 0,
    Label = 1,
    Matrix = 2,
    Form = 3,
    SpaceDelimited = 4,
    PipeDelimited = 5,
    DeepObject = 6
}
